spring:
  application:
    name: itoken-zipkin
  main:
    allow-bean-definition-overriding: true   #当遇到同样命名时，是否允许覆盖注册
  boot:
    admin:
      client:
        url: http://localhost:8084

#服务检测客户端与服务端都要添加下面这一段，才有效果
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

  #zipkin需要的配置
  metrics:
    web:
      server:
        auto-time-requests: false

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
