spring:
  application:
    name: itoken-zipkin
  main:
    allow-bean-definition-overriding: true   #当遇到同样命名时，是否允许覆盖注册
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false