spring:
  application:
    name: itoken-eureka
  zipkin:
    base-url: http://localhost:9411
  #服务监控客户端
  boot:
    admin:
      client:
        url: http://localhost:8084

#服务检测客户端与服务端都要添加下面这一段，才有效果
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否将自己注册到eureka,因为要构建集群，需要将自己注册到集群，所以需要开启
    registerWithEureka: true
    #表示是否从eureka获取到注册信息，这里为集群，所以应该开启
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.instance.hostname}:8861/eureka/
