spring:
  application:
    name: itoken-zuul
  zipkin:
    base-url: http://localhost:9411
  #服务监控客户端
  boot:
    admin:
      client:
        url: http://localhost:8084
#服务检测客户端与服务端都要添加下面这一段，才有效果
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#####api网关聚合器，统一管理服务的访问地址
zuul:
  routes:
    api-a:        #应用的名称随便取
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign
