spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://localhost:9411
  #服务监控客户端
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8084


#服务检测客户端与服务端都要添加下面这一段，才有效果
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/