spring:
  application:
    name: itoken-service-sso
  zipkin:
    base-url: http://localhost:9411
  #服务监控客户端
  boot:
    admin:
      client:
        url: http://localhost:8084
  datasource:
    druid:
      url: jdbc:mysql://192.168.145.128:3306/itoken-service-admin?serverTimezone=GMT%2B8
      username: root
      password: 123456
      initial-size: 1
      max-active: 20
    #thymeleaf配置
    thymeleaf:
      cacche: false #开发时关闭缓存，否则看不到实时页面
      mode: HTML5 #用严格的html
      encoding: UTF-8
      servlet:
        content-type: text/html

#服务检测客户端与服务端都要添加下面这一段，才有效果
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8503

mybatis:
  type-aliases-package: com.example.itokenservicesso.entity

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/